name: Week 2
on:
  push:
    branches:
      - week2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup Node Environment
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Get Count
        id: vars
        run: echo ::set-output name=count::$(cat ./.bit/.progress)

      - name: Step 1
        if: ${{steps.vars.outputs.count == 8 && github.event.head_commit.message != 'Update progress'}}
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        run: |
          npm install node-fetch
          npm install form-data
          npm install fs
          node .bit/tests/test.parseimage.js
      - name: Step 3
        if: ${{steps.vars.outputs.count == 10 && github.event.head_commit.message != 'Update progress'}}
        env:
          SUBSCRIPTION_KEY: ${{ secrets.SUBSCRIPTION_KEY }}
          API_ENDPOINT: ${{ secrets.API_ENDPOINT }}
        run: |
          node .bit/tests/test.secrets2.js
      - name: Step 5
        if: ${{steps.vars.outputs.count == 12 && github.event.head_commit.message != 'Update progress'}}
        env:
          FUNCTION_URL: ${{ secrets.FUNCTION_URL }}
        run: |
          npm install node-fetch
          npm install form-data
          npm install fs
          node .bit/tests/test.emotiondata.js
